name: SlackNotify
description: 'Notifies slack of the success or failure of the suite'
inputs:
  suite:
    description: "Suite that's running"
    required: true
  k8s_version:
    description: "Kubernetes version that this test ran against"
  url:
    description: "Webhook URL to send the Slack notification to"
    required: true
  git_ref:
    description: "The git commit, tag, or branch to check out. Requires a corresponding Karpenter snapshot release"
  event_name:
    description: "Type of event that triggered this test run"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.git_ref }}
    - shell: bash
      run: |
        if [[ ${{ inputs.event_name }} == "conformance" ]]; then
          RUN_NAME="conformance-periodic-${{ inputs.k8s_version }}-${{ inputs.suite }}"
        elif [[ ${{ inputs.event_name }} == "schedule" ]]; then
          RUN_NAME="${{ inputs.suite }}-periodic"
        else
          RUN_NAME="${{ inputs.suite }}-${GITHUB_SHA::7}"
        fi
        
        # Convert the RUN_NAME to all lowercase
        echo RUN_NAME=${RUN_NAME,,} >> $GITHUB_ENV
    - uses: ./.github/actions/e2e/slack/send-message
      if: ${{ job.status == 'success' }}
      with:
        url: ${{ inputs.url }}
        message: ":white_check_mark: ${{ env.RUN_NAME }} (https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})"
    - uses: ./.github/actions/e2e/slack/send-message
      if: ${{ job.status == 'failure' }}
      with:
        url: ${{ inputs.url }}
        message: ":x: ${{ env.RUN_NAME }} (https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})"