# This example provisioner will provision instances running Windows Server 2019

apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: windows2019
spec:
  requirements:
    - key: kubernetes.io/os
      operator: In
      values: ["windows"]
  providerRef:
    name: windows2019
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: windows2019
  annotations:
    kubernetes.io/description: "Nodes running Windows Server 2019"
spec:
  subnetSelector:
    karpenter.sh/discovery: "${CLUSTER_NAME}" # replace with your cluster name
  securityGroupSelector:
    karpenter.sh/discovery: "${CLUSTER_NAME}" # replace with your cluster name
  amiFamily: Windows2019
  metadataOptions:
    httpProtocolIPv6: disabled
    httpTokens: required