# This example provisioner will provision instances using the Windows 2022 EKS-Optimized AMI.
# The UserData defined in spec.UserData should be PowerShell commands
# and they will be prepended to a Karpenter managed section that will bootstrap the kubelet.
# This example also applies to the Windows 2019 EKS-Optimized AMI.

apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: windows2022
spec:
  requirements:
    - key: kubernetes.io/os
      operator: In
      values: ["windows"]
  providerRef:
    name: windows2022
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: windows2022
  annotations:
    kubernetes.io/description: "Nodes running Windows Server 2022"
spec:
  subnetSelector:
    karpenter.sh/discovery: "${CLUSTER_NAME}" # replace with your cluster name
  securityGroupSelector:
    karpenter.sh/discovery: "${CLUSTER_NAME}" # replace with your cluster name
  amiFamily: Windows2022
  metadataOptions:
    httpProtocolIPv6: disabled
    httpTokens: required
  userData: |
    New-Item -Path 'C:\temp\' -ItemType Directory
    New-Item -Path 'C:\temp\sample.txt' -ItemType File