name: AuthenticateAWS
description: 'Authenticates against the AWS account with OIDC'
runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: arn:aws:iam::071440425669:role/Github
        aws-region: us-east-1
