name: DumpLogs
description: 'Dump logs and debug information from the cluster after a test run'
inputs:
  account_id:
    description: "Account ID to access AWS"
    required: true
  role:
    description: "Role to access AWS"
    required: true
  region:
    description: "Region to access AWS"
    required: true
  cluster_name:
    description: 'Name of the cluster to be launched by eksctl'
    required: true
runs:
  using: "composite"
  steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::${{ inputs.account_id }}:role/${{ inputs.role }}
        aws-region: ${{ inputs.region }}
        role-duration-seconds: 21600
    - name: controller-logs
      shell: bash
      run: |
        aws eks update-kubeconfig --name ${{ inputs.cluster_name }}
        POD_NAME=$(kubectl get pods -n karpenter --no-headers -o custom-columns=":metadata.name" | tail -n 1)
        echo "logs from pod ${POD_NAME}"
        kubectl logs "${POD_NAME}" -n karpenter -c controller
    - name: describe-karpenter-pods
      shell: bash
      run: |
        aws eks update-kubeconfig --name ${{ inputs.cluster_name }}
        kubectl describe pods -n karpenter
    - name: describe-nodes
      shell: bash
      run: |
        aws eks update-kubeconfig --name ${{ inputs.cluster_name }}
        kubectl describe nodes